baseURL = "http://gepulog.github.io/gepulog/"
languageCode = "ja"
title = "gepulog"

theme = "hugo-thema-one"
googleAnalytics = ""

publishdir = "docs"

[params]
    navigation = ["archives.md", "about.md"]

